import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminRouter from "./admin";
import dataRouter from "./data";
const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(adminRouter);
router.use(dataRouter);
export default router;
